CONTIKI_PROJECT = oar
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += oar-debug.c
PROJECT_SOURCEFILES += oar-json.c
PROJECT_SOURCEFILES += oar-json-compact.c
PROJECT_SOURCEFILES += oar-json-micro.c
PROJECT_SOURCEFILES += oar-crypt.c

CONTIKI = ../..
include $(CONTIKI)/Makefile.include